---
git:
  depth: 1
language: node_js
node_js:
  - '0.10'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm update -g
  - npm install -qg bower gulp-cli
before_script:
  - bower install
after_success:
  - git config --global user.email "tracis@ci.org"
  - git config --global user.name "Travis Bot"
  - gulp publishing-machinery:publish
